In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [2]:
import pandas as pd
import numpy as np

index = pd.date_range(start="2010-01-01", end="2021-12-31")
data = np.random.randint(0, 100, size=(len(index), 5))

df = pd.DataFrame(data=data, index=index, columns=["Open", "High", "Low", "Close", "Volume"])
df.head()

            Open  High  Low  Close  Volume
2010-01-01    23    80   67     58       8
2010-01-02     9    29   36     35      42
2010-01-03     1    59    1     57      24
2010-01-04     1    76   60      5      15
2010-01-05    99    39   57     98      24

## 4.3.4 pandas.DataFrame.shift

In [3]:
df.shift(periods=1).head()

            Open  High   Low  Close  Volume
2010-01-01   NaN   NaN   NaN    NaN     NaN
2010-01-02  23.0  80.0  67.0   58.0     8.0
2010-01-03   9.0  29.0  36.0   35.0    42.0
2010-01-04   1.0  59.0   1.0   57.0    24.0
2010-01-05   1.0  76.0  60.0    5.0    15.0

In [4]:
df.shift(periods=-1).tail()

            Open  High   Low  Close  Volume
2021-12-27  75.0  96.0  75.0   57.0    37.0
2021-12-28  97.0  94.0  33.0   26.0    52.0
2021-12-29   4.0  42.0  11.0   91.0    77.0
2021-12-30  70.0  19.0  60.0   95.0    70.0
2021-12-31   NaN   NaN   NaN    NaN     NaN

In [5]:
df.shift(periods=-1).head()

            Open  High   Low  Close  Volume
2010-01-01   9.0  29.0  36.0   35.0    42.0
2010-01-02   1.0  59.0   1.0   57.0    24.0
2010-01-03   1.0  76.0  60.0    5.0    15.0
2010-01-04  99.0  39.0  57.0   98.0    24.0
2010-01-05  89.0  29.0  56.0   38.0    54.0

In [6]:
df.shift(periods=2, fill_value=0).head()

            Open  High  Low  Close  Volume
2010-01-01     0     0    0      0       0
2010-01-02     0     0    0      0       0
2010-01-03    23    80   67     58       8
2010-01-04     9    29   36     35      42
2010-01-05     1    59    1     57      24

In [7]:
df.shift(periods=2, freq="D").head()

            Open  High  Low  Close  Volume
2010-01-03    23    80   67     58       8
2010-01-04     9    29   36     35      42
2010-01-05     1    59    1     57      24
2010-01-06     1    76   60      5      15
2010-01-07    99    39   57     98      24

In [8]:
df.tshift(periods=1, freq="D").head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: tshift is deprecated and will be removed in a future version. Please use shift instead.
  """Entry point for launching an IPython kernel.

            Open  High  Low  Close  Volume
2010-01-02    23    80   67     58       8
2010-01-03     9    29   36     35      42
2010-01-04     1    59    1     57      24
2010-01-05     1    76   60      5      15
2010-01-06    99    39   57     98      24

In [9]:
df.tshift(periods=-1, freq="D").head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: tshift is deprecated and will be removed in a future version. Please use shift instead.
  """Entry point for launching an IPython kernel.

            Open  High  Low  Close  Volume
2009-12-31    23    80   67     58       8
2010-01-01     9    29   36     35      42
2010-01-02     1    59    1     57      24
2010-01-03     1    76   60      5      15
2010-01-04    99    39   57     98      24